# Site settings
title: Github Pages Tutorial
motto: Just figurin' it out!
email: bionicle.dragon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/github-pages-tutorial" # the subpath of your site, e.g. /blog/
url: "http://calebjones.net" # the base hostname & protocol for your site
twitter_username: porglezomp
github_username:  porglezomp

# Build settings
markdown: kramdown
